export const DEFAULT_THEME_COLOR: string = '#FF2E1F'
export const DEFAULT_WIDTH: string = '400px'
export const DEFAULT_HEIGHT: string = '450px'
export const DEFAULT_POSITION_TOP: string = '85px'

export const ID: string = 'search-js'
export const ID_HISTORIES: string = 'search-js-histories'
export const ID_RESULTS: string = 'search-js-result'
export const ID_LOADING: string = 'search-js-loading'

export const CLASS_CONTAINER: string = 'container'
export const CLASS_CLEAR_ICON: string = 'clear-icon'
export const CLASS_INPUT: string = 'search-input'
export const CLASS_ITEM: string = 'item'
export const CLASS_ITEMS: string = 'items'
export const CLASS_ITEM_CLOSE: string = 'item-close'
export const CLASS_MODAL: string = 'modal'
export const CLASS_MODAL_HEADER: string = 'modal-header'
export const CLASS_MODAL_FOOTER: string = 'modal-footer'
export const CLASS_MODAL_CONTENT: string = 'modal-content'

export const ATTR_DATA_PAYLOAD: string = 'data-payload'
