export const DEFAULT_THEME_COLOR = '#FF2E1F'
export const DEFAULT_WIDTH = '400px'
export const DEFAULT_HEIGHT = '450px'
export const DEFAULT_POSITION_TOP = '85px'

export const ID = 'search-js'
export const ID_HISTORIES = 'search-js-histories'
export const ID_RESULTS = 'search-js-result'
export const ID_LOADING = 'search-js-loading'

export const CLASS_CONTAINER = 'container'
export const CLASS_CLEAR_ICON = 'clear-icon'
export const CLASS_INPUT = 'search-input'
export const CLASS_ITEM = 'item'
export const CLASS_ITEMS = 'items'
export const CLASS_ITEM_CLOSE = 'item-close'
export const CLASS_MODAL = 'modal'
export const CLASS_MODAL_HEADER = 'modal-header'
export const CLASS_MODAL_FOOTER = 'modal-footer'
export const CLASS_MODAL_CONTENT = 'modal-content'

export const ATTR_DATA_PAYLOAD = 'data-payload'
